version: '3'

services:
  apixdatabase:
    image: mysql:5.6
    ports:
      - 3306:3306
    hostname: database
    volumes:
      - .var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=apix
