server:
    port: 8181
    servlet:
        context-path: /payment/v1

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/apix
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                show_sql: true
                dialect: org.hibernate.dialect.MySQL5Dialect

ms-register:
    registrations:
        endpoint: http://localhost:8080/register/v1/registrations

notification:
    twilio:
        account-sid: testeaccount
        auth-token: authToken
        origin-phone: originPhone