server:
    port: ${PORT}
    servlet:
        context-path: /payment/v1

spring:
    datasource:
        url: ${DATABASE_URL}
        username: ${DATABASE_USER}
        password: ${DATABASE_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                show_sql: true
                dialect: org.hibernate.dialect.MySQL5Dialect

ms-register:
    registrations:
        endpoint: ${REGISTER_ENDPOINT}

notification:
    twilio:
        account-sid: ${TWILIO_ACCOUNT_SID}
        auth-token: ${TWILIO_ACCOUNT_TOKEN}
        origin-phone: ${TWILIO_ORIGIN_PHONE}